FROM node:lts-alpine

# Переменные окружения для pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PNPM_DISABLE_SELF_UPDATE_CHECK=true
ENV PNPM_STORE_PATH=/pnpm/store

WORKDIR /app

RUN corepack enable

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm fetch

COPY client/package.json ./client/

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --offline --frozen-lockfile --filter @nosql/client

COPY client ./client

EXPOSE 5173

# Запуск Vite dev-сервера с прослушиванием всех интерфейсов (--host)
CMD ["pnpm", "--filter", "@nosql/client", "exec", "vite", "--host"]