services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - server
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./server/.env
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: neo4j:4.4-community
    container_name: db
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads_data:
  neo4j-data:

